name: Publish to NPM

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: 'build & Pack & Publish'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Extract version from tag
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV

      - run: npm ci
      - run: npm run build
      - run: npm publish --tag ${VERSION}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}